name: Publish
on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 3 * * *'

jobs:
  publish-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#        with:
#          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Installing
        run: yarn

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test

      - name: Building and Starting
        run: yarn start

      - name: Updating README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "bot"
          git config user.email "tynik@users.noreply.github.com"
          git commit README.md -m "Updated README.md automatically with aggregated info of smart contracts" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
