name: Publish
on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 3 * * *'

jobs:
  publish-info:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Pull the latest changes
        run: |
          git submodule update
          git commit smart-contract-sanctuary-ethereum -m "Updating smart-contract-sanctuary-ethereum to latest"
          git push origin

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Installing
        run: yarn

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test

      - name: Building and Starting
        run: yarn start

      - name: Updating README.md
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit README.md -m "Updated README.md automatically with aggregated info of smart contracts" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
